# Generated by Django 6.0.3 on 2026-03-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("price", models.DecimalField(decimal_places=6, max_digits=20)),
                ("as_of", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
