# Generated by Django 6.0.3 on 2026-03-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_paper_trading"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20, unique=True)),
                ("price", models.DecimalField(decimal_places=6, max_digits=20)),
                ("open_price", models.DecimalField(decimal_places=6, max_digits=20)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
    ]
