# Generated by Django 6.0.3 on 2026-03-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_intelligence_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="confidence",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="intent",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="model_used",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reasoning_flags",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="retrieval_used",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sources",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="memory_summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
